file_format: "1"
id: manuform
Name: manuform_ble
type: shield
url: https://github.com/jtcdbob/zmk-config-24/
requires:
  - nice_nano_v2
exposes:
  - i2c_oled
features:
  - keys
  - encoders
siblings:
  - manuform_left
  - manuform_right
